### ISSUE TITLE
If you dont host a live version of your app I can't test it

### ISSUE THREAD

**Issue by Razpudding** [BerendPronk/minor-touch-cmd#49]
Since I don't have a specific db up and running for this app I can't test its functionality.

**Comment by BerendPronk** [comment]
I understand the troubles. However, in this stage of development I rather put my focus on actually creating the application, instead of deploying it somewhere.

The decision to have a closed code-review (because of the CSS Day event interruption) wasn't really in our advantage with this specific project. I never learnt to deploy a Node application with a MySQL database on a live server. I had little to no time to get a grip on that, my apologies.
